#!/usr/bin/env python3

import sys

from cpu import CPU

cpu = CPU()

for cycle, x in cpu.run(sys.argv[1:]):
    cursor = (cycle - 1) % 40

    if abs(cursor - x) < 2:
        print('#', end='')
    else:
        print('.', end='')

    if cursor == 39:
        print()
