#!/usr/bin/env zsh

typeset -i current=0 max=0

IFS="\n"

while read -r line; do
    if [[ $line ]]; then
        (( current += line ))
    else
        if (( current > max )); then
            max=$current
        fi
        current=0
    fi
done

print $max
