#!/usr/bin/env zsh

typeset -i current=0 first=0 second=0 third=0

IFS="\n"

while read -r line; do
    if [[ $line ]]; then
        (( current += line ))
    else
        if (( current > third )); then
            third=$current
        fi

        if (( current > second )); then
            third=$second
            second=$current
        fi

        if (( current > first )); then
            second=$first
            first=$current
        fi

        current=0
    fi
done

print $(( first + second + third ))
