#!/usr/bin/env python3

import fileinput, sys

from graph import *

graph = Graph()

r = 0
c = 0
for line in fileinput.input(sys.argv[1:]):
    c = 0
    for ch in line[:-1]:
        v = Vertex(r,c)
        graph.distances[v] = Infinity
        graph.neighbors[v] = []
        if ch == 'S':
            graph.start = v
            graph.distances[v] = 0
            ch = 'a'
        elif ch == 'E':
            graph.end = v
            ch = 'z'
        graph.heights[v] = ch
        c += 1
    r += 1
graph.n_rows = r
graph.n_cols = c

for r in range(graph.n_rows):
    for c in range(graph.n_cols):
        v = Vertex(r,c)
        for neighbor in [Vertex(r-1,c), Vertex(r,c+1), Vertex(r+1,c), Vertex(r,c-1)]:
            if neighbor.r < 0 or neighbor.r == graph.n_rows:
                continue
            if neighbor.c < 0 or neighbor.c == graph.n_cols:
                continue
            if codepoint(graph.heights[v]) >= (codepoint(graph.heights[neighbor])-1):
                graph.neighbors[v].append(neighbor)

graph.compute()

print(graph.distances[graph.end])
